dt:
  pre: maven://org.springframework.cloud.launcher:spring-cloud-launcher-
  ver: ${launcher.version}
  mem: 128m
  opts: -XX:TieredStopAtLevel=1 -noverify

spring:
  cloud:
    maven:
      remote-repositories:
        central:
          url: http://repo1.maven.org/maven2
        spring-milestone:
          url: http://repo.spring.io/milestone
        spring-snapshot:
          url: http://repo.spring.io/snapshot
    launcher:
      deployables:
        configserver:
          coordinates: ${dt.pre}configserver:${dt.ver}
          port: 8888
          waitUntilStarted: true
          order: -100
          properties:
            spring.cloud.deployer.memory: ${dt.mem}
            spring.cloud.deployer.local.javaOpts: ${dt.opts}
        dataflow:
          coordinates: ${dt.pre}dataflow:${dt.ver}
          port: 9393
          properties:
            spring.cloud.deployer.memory: ${dt.mem}
            spring.cloud.deployer.local.javaOpts: ${dt.opts}
        eureka:
          coordinates: ${dt.pre}eureka:${dt.ver}
          port: 8761
          message: To see the dashboard open http://localhost:8761
          disabled:
            eureka.client.enabled: false
          properties:
            spring.cloud.deployer.memory: ${dt.mem}
            spring.cloud.deployer.local.javaOpts: ${dt.opts}
        h2:
          coordinates: ${dt.pre}h2:${dt.ver}
          port: 9095
          message: Connect on jdbc:h2:tcp://localhost:9096/./target/test, web console at http://localhost:9095
          waitUntilStarted: true
          order: -50
          enabled:
            spring.datasource.url: jdbc:h2:tcp://localhost:9096/./target/test
          properties:
            spring.cloud.deployer.memory: ${dt.mem}
            spring.cloud.deployer.local.javaOpts: ${dt.opts}
        hystrixdashboard:
          coordinates: ${dt.pre}hystrixdashboard:${dt.ver}
          port: 7979
          properties:
            spring.cloud.deployer.memory: ${dt.mem}
            spring.cloud.deployer.local.javaOpts: ${dt.opts}
        kafka:
          coordinates: ${dt.pre}kafka:${dt.ver}
          port: 9091
          waitUntilStarted: true
          order: -200
          disabled: 
            spring.cloud.bus.enabled: false
          properties:
            spring.cloud.deployer.memory: ${dt.mem}
            spring.cloud.deployer.local.javaOpts: ${dt.opts}
        zipkin:
          coordinates: ${dt.pre}zipkin:${dt.ver}
          port: 9411
          order: 0
          properties:
            spring.cloud.deployer.memory: ${dt.mem}
            spring.cloud.deployer.local.javaOpts: ${dt.opts}
      deploy: ${launcher.deploy:configserver,eureka}
