dt:
  pre: maven://org.springframework.cloud.launcher:spring-cloud-launcher-
  ver: ${launcher.version}
  mem: 128m
  opts: -XX:TieredStopAtLevel=1 -noverify

spring:
  cloud:
    maven:
      remote-repositories:
        central:
          url: http://repo1.maven.org/maven2
        spring-milestone:
          url: http://repo.spring.io/milestone
        spring-snapshot:
          url: http://repo.spring.io/snapshot
    launcher:
      deployables:
        configserver:
          coordinates: ${dt.pre}configserver:${dt.ver}
          port: 8888
          waitUntilStarted: true
          order: -100
          properties:
            spring.cloud.deployer.memory: ${dt.mem}
            spring.cloud.deployer.local.javaOpts: ${dt.opts}
          application-properties:
            management.security.enabled: false
        dataflow:
          coordinates: ${dt.pre}dataflow:${dt.ver}
          port: 9393
          properties:
            spring.cloud.deployer.memory: ${dt.mem}
            spring.cloud.deployer.local.javaOpts: ${dt.opts}
          application-properties:
            management.security.enabled: false
        eureka:
          coordinates: ${dt.pre}eureka:${dt.ver}
          port: 8761
          message: To see the dashboard open http://localhost:8761
          disabled:
            eureka.client.enabled: false
          properties:
            spring.cloud.deployer.memory: ${dt.mem}
            spring.cloud.deployer.local.javaOpts: ${dt.opts}
          application-properties:
            management.security.enabled: false
        h2:
          coordinates: ${dt.pre}h2:${dt.ver}
          port: 9095
          message: Connect on jdbc:h2:tcp://localhost:9096/mem:test, web console at http://localhost:9095
          waitUntilStarted: true
          order: -50
          enabled:
            spring.datasource.url: jdbc:h2:tcp://localhost:9096/mem:test
            spring.dataflow.embedded.database.enabled: false
          properties:
            spring.cloud.deployer.memory: ${dt.mem}
            spring.cloud.deployer.local.javaOpts: ${dt.opts}
          application-properties:
            management.security.enabled: false
        hystrixdashboard:
          coordinates: ${dt.pre}hystrixdashboard:${dt.ver}
          port: 7979
          properties:
            spring.cloud.deployer.memory: ${dt.mem}
            spring.cloud.deployer.local.javaOpts: ${dt.opts}
          application-properties:
            management.security.enabled: false
        kafka:
          coordinates: ${dt.pre}kafka:${dt.ver}
          port: 9091
          waitUntilStarted: true
          order: -200
          disabled: 
            spring.cloud.bus.enabled: false
          properties:
            spring.cloud.deployer.memory: ${dt.mem}
            spring.cloud.deployer.local.javaOpts: ${dt.opts}
          application-properties:
            management.security.enabled: false
        stubrunner:
          coordinates: ${dt.pre}stubrunner:${dt.ver}
          port: 8750
          message: To see the registered stubs open http://localhost:8750/stubs
          order: 0
          properties:
            spring.cloud.deployer.memory: ${dt.mem}
            spring.cloud.deployer.local.javaOpts: ${dt.opts}
          application-properties:
            management.security.enabled: false
      deploy: ${launcher.deploy:configserver,eureka}

---
spring:
  profiles: rabbit
  cloud:
    launcher:
      deployables:
        configserver:
          properties:
            spring.cloud.deployer.thin.profile: rabbit
          application-properties:
            spring.cloud.bus.enabled: true
        eureka:
          properties:
            spring.cloud.deployer.thin.profile: rabbit
          application-properties:
            spring.cloud.bus.enabled: true
        h2:
          properties:
            spring.cloud.deployer.thin.profile: rabbit
          application-properties:
            spring.cloud.bus.enabled: true
        dataflow:
          properties:
            spring.cloud.deployer.thin.profile: rabbit
          application-properties:
            spring.cloud.bus.enabled: true
        hystrixdashboard:
          properties:
            spring.cloud.deployer.thin.profile: rabbit
          application-properties:
            spring.cloud.bus.enabled: true
        stubrunner:
          properties:
            spring.cloud.deployer.thin.profile: rabbit
          application-properties:
            spring.cloud.bus.enabled: true